### ISSUE TITLE
Description column

### ISSUE THREAD

**Issue by omergulen** [wwdc/2019#12] opened 2019-03-25 18:04 UTC
I think adding a description column would be great, once I looked up for the last years projects I always desired to know what is it about and sometimes I went to code, sometimes I went to Youtube but I think 1-2 sentence description would be great.

**Comment by lucashoeft** [comment] 2019-03-25 18:10
Check #2

**Comment by omergulen** [comment] 2019-03-25 18:19
I definitely didn't see it xd I can try to help with that!

**Comment by Schemetrical** [comment] 2019-03-25 22:22
Closed as duplicate of #2

**Closed by Schemetrical** 2019-03-25 22:22 UTC
